# Root logger configuration
log4j.rootLogger=OFF, stdout

# Console output settings
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d [%t] %-5p %c - %m%n

# Kafka broker logging levels
#log4j.logger.kafka.coordinator.transaction=DEBUG
#log4j.logger.kafka.request.logger=DEBUG


# log4j.logger.kafka=DEBUG
# log4j.logger.org.apache.kafka=DEBUG
# log4j.logger.org.apache.kafka.controller=OFF
# log4j.logger.org.apache.kafka.metadata=OFF
# log4j.logger.org.apache.kafka.coordinator=OFF
# log4j.logger.org.apache.kafka.image=OFF
# log4j.logger.kafka.server.metadata=OFF
# log4j.logger.org.apache.raft=OFF
# log4j.logger.org.apache.kafka.raft=OFF
# log4j.logger.org.apache.kafka.timeline=OFF
# log4j.logger.org.apache.kafka.deferred=OFF
# log4j.logger.org.apache.common.network=OFF
# log4j.logger.org.apache.kafka.clients=OFF
# 
# log4j.logger.kafka.log=OFF
# log4j.logger.kafka.network=OFF
# log4j.logger.kafka.server=OFF
# log4j.logger.kafka.network.Processor=INFO
# log4j.logger.kafka.log.LogCleaner=INFO
