services:
  redpanda-0:
    privileged: true
    image: redpandadata/redpanda:latest
    network_mode: host
    command:
      - redpanda
      - start
      - --mode dev-container
      - --smp 1
      - --set redpanda.admin=[{"address":"0.0.0.0","port":9644}]
      - --schema-registry-addr=0.0.0.0:8072
      - --pandaproxy-addr=0.0.0.0:8082
      - --advertise-pandaproxy-addr=localhost:8082
      - --kafka-addr=0.0.0.0:9092
      - --advertise-kafka-addr=localhost:9092
      - --rpc-addr=0.0.0.0:33145
      - --advertise-rpc-addr=localhost:33145

  redpanda-1:
    privileged: true
    image: redpandadata/redpanda:latest
    network_mode: host
    depends_on:
      - redpanda-0
    command:
      - redpanda
      - start
      - --mode dev-container
      - --smp 1
      - --set redpanda.admin=[{"address":"0.0.0.0","port":9645}]
      - --schema-registry-addr=0.0.0.0:8073
      - --pandaproxy-addr=0.0.0.0:8083
      - --advertise-pandaproxy-addr=localhost:8083
      - --kafka-addr=0.0.0.0:9093
      - --advertise-kafka-addr=localhost:9093
      - --rpc-addr=0.0.0.0:33146
      - --advertise-rpc-addr=localhost:33146
      - --seeds="localhost:33145"

  redpanda-2:
    privileged: true
    image: redpandadata/redpanda:latest
    network_mode: host
    depends_on:
      - redpanda-1
    command:
      - redpanda
      - start
      - --mode dev-container
      - --smp 1
      - --set redpanda.admin=[{"address":"0.0.0.0","port":9646}]
      - --schema-registry-addr=0.0.0.0:8074
      - --pandaproxy-addr=0.0.0.0:8084
      - --advertise-pandaproxy-addr=localhost:8084
      - --kafka-addr=0.0.0.0:9094
      - --advertise-kafka-addr=localhost:9094
      - --rpc-addr=0.0.0.0:33147
      - --advertise-rpc-addr=localhost:33147
      - --seeds="localhost:33145"
